language: node_js
node_js:
 - lts/*

cache:
 npm: true
 directories:
  - node_modules
  - ~/.cache

branches:
 only:
  - master

install:
 - npm install

script:
 - npm run build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com